server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

      # New scrape target for C:\docker_persistence\targettest.log
      - job_name: targettest
        static_configs:
          - targets:
              - host.docker.internal:9081
            labels:
              job: testjob
              __path__: c:\docker_persistence\promtail\log\*.log